---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ include "wordpress.fullname" . }}
type: Opaque
data:
  WORDPRESS_TABLE_PREFIX: {{ .Values.wordpress.tablePrefix | b64enc }}
  {{- if and .Values.wordpress.configExtra (not .Values.wordpress.configExtraConfigMap.name) (not .Values.wordpress.configExtraSecret.name) }}
  {{- $configextra := .Values.wordpress.configExtra }}
  {{- $url := .Values.wordpress.url }}
  {{/* If memcached is enabled and createconfig is true, append PHP memcached servers array */}}
  {{- $memcfg := "" }}
  {{- if and .Values.memcached.enabled .Values.memcached.createconfig }}
  {{- $memcfg = printf "$memcached_servers = array('default' => array('%s:%v'));\n" (include "wordpress.memcached.fullname" .) (.Values.memcached.service.port) }}
  {{- end }}
  WORDPRESS_CONFIG_EXTRA: {{ printf "%s;define('WP_HOME', '%s');define('WP_SITEURL', '%s');%s" $configextra $url $url $memcfg | b64enc }}
  {{- end }}
  {{- if .Values.mariadb.enabled }}
  {{- $host := include "wordpress.mariadb.fullname" . }}
  {{- $port := default 3306 .Values.mariadb.service.port }}
  WORDPRESS_DB_NAME: {{ .Values.mariadb.auth.database | b64enc }}
  WORDPRESS_DB_HOST: {{ printf "%s:%v" $host $port | b64enc }}
  WORDPRESS_DB_USER: {{ .Values.mariadb.auth.username | b64enc }}
  {{- else }}
  {{- $host := .Values.externalDatabase.host }}
  {{- $port := default 3306 .Values.externalDatabase.port }}
  WORDPRESS_DB_NAME: {{ .Values.externalDatabase.database | b64enc }}
  WORDPRESS_DB_HOST: {{ printf "%s:%v" $host $port | b64enc }}
  {{- if and (not .Values.mariadb.enabled) (not .Values.externalDatabase.existingSecret) }}
  {{- if .Values.externalDatabase.username }}
  WORDPRESS_DB_USER: {{ .Values.externalDatabase.username | b64enc }}
  {{- end }}
  {{- if .Values.externalDatabase.password }}
  WORDPRESS_DB_PASSWORD: {{ .Values.externalDatabase.password | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- if and .Values.wordpress.init.enabled (empty .Values.wordpress.init.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-init
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ include "wordpress.fullname" . }}-init
type: Opaque
data:
  wordpress.username: {{ .Values.wordpress.init.username | b64enc }}
  wordpress.password: {{ .Values.wordpress.init.password | b64enc }}
  wordpress.email: {{ .Values.wordpress.init.email | b64enc }}
{{- end }}
{{ if .Values.metrics.wordpress.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metrics.wordpress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ include "metrics.wordpress.fullname" . }}
type: Opaque
data:
  {{ if (empty .Values.metrics.wordpress.existingSecret) }}
  wordpress.metrics.token: {{ .Values.metrics.wordpress.serviceMonitor.token | b64enc }}
  {{- end }}
  wordpress.metrics.encryptionKey: {{ randAlphaNum 32 | b64enc }}
{{- end }}